name: gamify
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  overlay_support: ^2.1.0
  soundpool: ^2.3.0
  intl: any
  flutter_localization: any
  cupertino_icons: ^1.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.2
  provider: ^6.0.5
  flutter_carousel_slider: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
  path_provider: ^2.0.15
  audioplayers:
  flame_forge2d:
  flame:
  flame_audio:
  bonfire: ^3.2.0
  flame_splash_screen: ^0.1.0
  lottie: ^1.4.1
  rating_dialog:
  share_plus: ^4.0.10+1
  share: ^2.0.4
  firebase_core: ^2.15.0
  firebase_auth:
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  cloud_firestore: any
  ionicons: ^0.2.2
  google_fonts:
  infinite_carousel: ^1.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  flame_tiled: ^1.18.3
  equatable: ^2.0.5
  flutter_native_splash: ^2.3.9
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    #pacman
    - assets/pacman/images/
    #spacescape
    - assets/images/
    #tetris
    - assets/tetris/assets/
    - assets/tetris/assets/audios/
    #jumper
    - assets/
    #main images
    - assets/mainimages/
    #dino
    - assets/images/dino/
    - assets/images/cacti/
    - assets/images/ptera/

    #dungeon
    - assets/audio/
    - assets/tiles/
    - assets/images/Menu/Buttons/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Traps/Saw/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/
    - assets/images/Menu/

  fonts:
    - family: BungeeInline
      fonts:
        - asset: assets/spacescape/fonts/BungeeInline/BungeeInline-Regular.ttf

    - family: DaveysDoodleface
      fonts:
        - asset: fonts/DaveysDoodleface.ttf
    - family: Normal
      fonts:
        - asset: fonts/font_pixel.ttf

    - family: Magic4
      fonts:
        - asset: assets/fonts/DiloWorld-mLJLv.ttf

    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PixelifySans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PixelifySans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PixelifySans-SemiBold.ttf
          weight: 600
